### ISSUE TITLE
favicons in tabs address

### ISSUE THREAD

**Issue by klaszlo** [billiob/terminology#10]
Hi,

My current problem with terminology is the lack of tab customization.
It only shows the file path, and it is hard to distinguish.

So I would like a feature to display a small icon (like the browser's favicon) to the left of the tab's title.
And a configuration file something like this:
'/home/USER/Desktop/projects/mysecretprojects/*' 'path/to/my_favicon.png'

So if I'm inside the 'mysecretprojects' (and any subfolder inside it),
 terminology would display the my_favicon.png file in the tab bar.

Exactly how it is done in webbrowsers. 

I know it is more a feature request then an issue, but bugging me so hard...

Thank you for your attention.

**Comment by billiob** [comment]
I've created https://phab.enlightenment.org/T2089 .

**Comment by billiob** [comment]
Should follow up on https://phab.enlightenment.org/T2089 .
