### ISSUE TITLE
Alt-Enter does not work with Midnight Commander mc

### ISSUE THREAD

**Issue by klaszlo** [billiob/terminology#11]
Hi,

Alt-Enter is supposed to past the current file on midnight commander's 
own command line (below the blue panel).

After disabling the default 'Paste primary clipboard' shortcut action for Alt-Enter, the behaviour
for Alt-Enter is exactly the same as simply pressing Enter.
(ie. if I'm on a directory it steps inside the directory, if I'm on a file which is recognized by mc, 
then it opens it via it's helper, like on a .png it launch eog by default).

Breaking this shortcut inside mc, effectively kills fast renaming (mv [HIT ALT-ENTER TWICE]).

I would like to see a fix for this issue.

**Comment by billiob** [comment]
I've fixed it in 9814b10ad2.
