### ISSUE TITLE
Nyanology changes color schemes?

### ISSUE THREAD

**Issue by AvalancheTheory** [billiob/terminology#15]
Hey this might be silly, but I use the Nyanology for my theme in terminology and it appears to change the colors in the terminal? Or at least it changes the colorscheme in vim... which is really super unfortunate. Is there anyway to fix that? I like the cat as a cursor.

**Comment by billiob** [comment]
Do you have the same issue with the default theme?
Do you still have that issue if you change the value of the check-box in the Settings menu → Behavior → Set TERM to xterm-256color (you need to restart terminology after changing that) ?

**Comment by AvalancheTheory** [comment]
Changing to 256 colors did it for me! Thank you!
