### ISSUE TITLE
Ctrl-H

### ISSUE THREAD

**Issue by test-account-0** [billiob/terminology#16]
Ctrl-H is doing the same thing as backspace. I'm using that shortcut in tmux to change panes.

I cannot find any way to disable default behaviour.

**Comment by billiob** [comment]
What distro are you using?
Is it the same if you tick "BackArrow sends Del (instead of BackSpace)" in Settings → Behavior?

**Comment by test-account-0** [comment]
Linux MInt 17 Qiana.

Nope. It doesn't affect that.

**Comment by billiob** [comment]
I forgot to tell you, but you need to restart terminology after changing that setting.

**Comment by Makohoek** [comment]
Hi,
I am also using `Ctrl+H` for navigating within tmux.

`Ticking "BackArrow sends Del (instead of BackSpace)" in Settings → Behavior` as @billiob suggested fixes the problem for me.
I restarted terminology, and problem solved! :+1: 

Thanks a lot :)
