### ISSUE TITLE
New line when pasting

### ISSUE THREAD

**Issue by test-account-0** [billiob/terminology#17]
When I'm pasting something in terminology sometimes appears a new line. This can be annoying. Especially when creating some potentially dangerous command.

**Comment by billiob** [comment]
If you go till the end of the line, it will copy the "newline" character. Which version of Terminology are you using?

**Comment by test-account-0** [comment]
I'm not copying "newline" character. Pasting to any other terminal emulator I have doesn't show any "newlines".

0.8.99 from ppa  enlightenment-git

**Comment by billiob** [comment]
Could you give me concrete example when it occurs?

**Comment by billiob** [comment]
No reply in few months. Closing the issue.

**Comment by test-account-0** [comment]
Sorry for that.
I just switched to urxvt and forgot about the issue.

It still happens in terminology 0.9.99

It happens always when I'm copying and pasting something holding ctrl.

Try it. Just hold Ctrl, copy some text and paste it with middle mouse button.

I need to hold Ctrl because I'm using tmux.

**Comment by billiob** [comment]
If you copy:
```
aa
bb
```
do you expect to paste `aabb` ?

**Comment by test-account-0** [comment]
No, if I copy:

```
aa
bb
```
I expect to paste:
```
aa
bb
```
and not

```
aa
bb
<===== new line
```

**Comment by billiob** [comment]
Should be fixed in b74cfc752a6d032fd4a6b280e8505be11f4451c3

**Comment by test-account-0** [comment]
Yes. It is working now as expected. Thanks.
