### ISSUE TITLE
'Reset font size' does not work

### ISSUE THREAD

**Issue by limasierra** [billiob/terminology#18]
Hi,

I'm having trouble with the 'Reset font size' shortcut (Ctrl + Alt + 0). Apparently, a new Terminology window cannot get the font size setting, and Ctrl + Alt + 0 resets my font size to the minimum, 5px.

It does however work if I change the font size setting and the 'Temporary' checkbox is not checked. But then again, it works only for that instance of Terminology.

A quick workaround until this is fixed:
In `/src/bin/termio.c`, line 472 (in function `_font_size_set`):
Change the line `if (size < 5) size = 5;` to `if (size < 5) size = 12;` or whatever your preferred font size is :)

Keep up the excellent work!

Kind regards,
Laurent

**Comment by billiob** [comment]
Changing the font size through key bindings only changes the settings locally and temporarily.
Resetting the font size shouldn't work like that. I'll try to fix it.

**Comment by limasierra** [comment]
Hi,

I can confirm that it works now, many thanks!

Btw: Nice C code you have there, really a pleasure to read!

**Comment by billiob** [comment]
Thank you for your kind words, it is appreciated.
