### ISSUE TITLE
fatal error on launch on_low_battery_get_cb()

### ISSUE THREAD

**Issue by joaop** [billiob/terminology#19]
bash$ terminology 
ERR<3071>:ecore_system_upower modules/ecore/system/upower/ecore_system_upower.c:74 _on_low_battery_get_cb() Message error org.freedesktop.DBus.Error.InvalidArgs - No such property OnLowBattery
Segmentation fault

Debian 8.0 / Pentium 4 / 2GB RAM
Linux home 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) i686 GNU/Linux

What else can I say to help you ?

**Comment by billiob** [comment]
What versions of EFL, elementary are you using?
Can you get a backtrace with gdb?

**Comment by billiob** [comment]
No reply in few months. Closing the issue.
