### ISSUE TITLE
How can I compile it in Ubuntu?

### ISSUE THREAD

**Issue by kensully** [billiob/terminology#21]
Hi,
I've much heard of **terminology** terminal emulator. I am Ubuntu 14.04 platform. I cloned this repo and ran `./autogen.sh` but I met missing elementary library. How can I workaround that dependency?
Since elementary is a desktop environment, I fear that it should be  huge in size.
It's pity that other Linux distros can not enjoy **terminology**
Regards.
Kenn

**Comment by billiob** [comment]
You should use packages from bodhi linux : http://www.bodhilinux.com/ .

**Comment by akanouras** [comment]
@kensully You can find E19 & Terminology 0.8.0 here:
https://launchpad.net/~niko2040/+archive/ubuntu/e19?field.series_filter=trusty
