### ISSUE TITLE
Compound unicode characters render incorrectly

### ISSUE THREAD

**Issue by jhass** [billiob/terminology#23]
I'm using terminology inside Gnome on Archlinux. When it comes to Unicode compound characters, the rendering is often wrong, be it messing up the entire line, not actually doing the compound or in this case adding a space afterwards:

![](http://cloud.aeshna.de/u/mrzyx/screenshots/screenshot_20150722_134924.png)

**Comment by billiob** [comment]
It's not supported for the moment. I'll have to work on it someday.

**Comment by billiob** [comment]
Please follow on https://phab.enlightenment.org/T560
