### ISSUE TITLE
Split via command line is not working

### ISSUE THREAD

**Issue by akadaedalus** [billiob/terminology#26]
I cannot find any variation of the split command line argument for terminology that works, including the example in the man page.  They all just give me a new terminal with no split.  I was hoping to create a quick shortcut that splits with the right commands in each window so I don't have to do it manually (which works).

This is version 0.9.1 built on Gentoo Linux.

**Comment by billiob** [comment]
it is indeed totally broken

**Comment by billiob** [comment]
It is fixed in 86a596d9466. Thank you.
