### ISSUE TITLE
"<" is entered as ">"

### ISSUE THREAD

**Issue by hut8** [billiob/terminology#27]
Hey there. I seem to have found quite a strange bug. I cloned this repo and compiled from master just to make sure it hadn't been resolved. It seems as though every time I type `<`,  the character `>` appears. This isn't a rendering issue; I verified that when running emacs or nano in a terminal, and typing `<` then saving the file, then it does in fact save the `>`. The opposite doesn't happen, so now I have two keys that enter `>`. What's up with this? I'm on a new install of FC 22.

**Comment by billiob** [comment]
That is weird! What is the keyboard layout you're using? If you launch `elementary_test`, does it also happen in the search bar?

**Comment by billiob** [comment]
Output from `xev` on FC23 (thanks to q-tip):

    KeyPress event, serial 36, synthetic NO, window 0x2600001,
        root 0xfa, subw 0x0, time 14570839, (150,35), root:(187,136),
        state 0x0, keycode 62 (keysym 0xffe2, Shift_R), same_screen YES,
        XLookupString gives 0 bytes:
        XmbLookupString gives 0 bytes:
        XFilterEvent returns: False
     
    KeyPress event, serial 36, synthetic NO, window 0x2600001,
        root 0xfa, subw 0x0, time 14576074, (150,35), root:(187,136),
        state 0x1, keycode 25 (keysym 0x3c, less), same_screen YES,
        XKeysymToKeycode returns keycode: 94
        XLookupString gives 1 bytes: (3c) "<"
        XmbLookupString gives 1 bytes: (3c) "<"
        XFilterEvent returns: False
     
    KeyRelease event, serial 36, synthetic NO, window 0x2600001,
        root 0xfa, subw 0x0, time 14576169, (150,35), root:(187,136),
        state 0x1, keycode 25 (keysym 0x3c, less), same_screen YES,
        XKeysymToKeycode returns keycode: 94
        XLookupString gives 1 bytes: (3c) "<"
        XFilterEvent returns: False
     
    KeyPress event, serial 36, synthetic NO, window 0x2600001,
        root 0xfa, subw 0x0, time 14577076, (150,35), root:(187,136),
        state 0x1, keycode 26 (keysym 0x3e, greater), same_screen YES,
        XLookupString gives 1 bytes: (3e) ">"
        XmbLookupString gives 1 bytes: (3e) ">"
        XFilterEvent returns: False
     
    KeyRelease event, serial 36, synthetic NO, window 0x2600001,
        root 0xfa, subw 0x0, time 14577155, (150,35), root:(187,136),
        state 0x1, keycode 26 (keysym 0x3e, greater), same_screen YES,
        XLookupString gives 1 bytes: (3e) ">"
        XFilterEvent returns: False
     
    KeyRelease event, serial 36, synthetic NO, window 0x2600001,
        root 0xfa, subw 0x0, time 14578395, (150,35), root:(187,136),
        state 0x1, keycode 62 (keysym 0xffe2, Shift_R), same_screen YES,
        XLookupString gives 0 bytes:
        XFilterEvent returns: False

**Comment by billiob** [comment]
If you try to set `>` or `<`, has a key binding, which one do you get?

**Comment by weitjong** [comment]
I have the same problem on my 64-bit F23. Both '<' and '>' keys generate '>' in the terminal output. Using ```xev``` I can confirm both keys generates the same keyPress and KeyReleases events as yours above, i.e. '3c' for left angle bracket and '3e' for the right one.

> If you try to set > or < as a key binding, which one do you get?

When I tred to bind the keys, this is what happened.
1. ```ctrl``` + ```shift``` + ```,```  ==> nothing appear ('<' could NOT be bound)
2. ```ctrl``` + ```,``` ==> ```Ctrl+comma```
3. ```ctrl``` + ```shift``` + ```.``` ==> ```Ctrl+Shift+period``` ('>' could be bound)
4. ```ctrl``` + ```.``` ==> ```Ctrl+period```

**Comment by weitjong** [comment]
The discussion in this forum http://forums.fedoraforum.org/showthread.php?p=1755496#post1755496 indicates that it has somehow related to IM.

**Comment by billiob** [comment]
Could you guys please open the bug on https://phab.enlightenment.org/maniphest/task/create/ ?
I still have no idea on how to fix it.
