### ISSUE TITLE
Missing items in settings side bar

### ISSUE THREAD

**Issue by DoTheEvo** [billiob/terminology#29]
only single item is there - toolkit
[http://i.imgur.com/EvU9kgj.png](http://i.imgur.com/EvU9kgj.png)

I am on arch, with i3wm, infinality fonts and tried various themes and stuff.

there are also no icons in tabs in toolkit
[http://i.imgur.com/2x2xA0v.png](http://i.imgur.com/2x2xA0v.png)

rings any bells or its my very own issue that I will live with?

**Comment by billiob** [comment]
You should update elementary.

**Comment by DoTheEvo** [comment]
thanks, I went for elementary-git package and its working now

http://i.imgur.com/SwbEmoh.jpg
