### ISSUE TITLE
Font Issues

### ISSUE THREAD

**Issue by aiudirog** [billiob/terminology#30]
I have been using Terminology for a while without any issues but last night when I opened it up, I ended up changing my background image to a gif (just to see if I could and it worked which was pretty cool) but now the fonts are all screwed up.

By screwed up, I mean:
For scalable fonts: The letters are all offset vertically, making the text look wavy.
Example: 
    ![image](https://cloud.githubusercontent.com/assets/5399935/11308205/dd2f1230-8f8a-11e5-8d01-01177a055330.png)
For bitmapped fonts: The cursor always appears 1.5 text lines above where it needs to be and the top line of the terminal is blank.
Example:
    ![image](https://cloud.githubusercontent.com/assets/5399935/11308233/070207c0-8f8b-11e5-913e-a34b62aa02fd.png)

I have tried removing .config/terminology and reinstalling. Also I have reinstalled efl & elementary packages (and clearing their config files). The screen shots are from the most recent commit which I built from source to see if that would fix it, but no dice there.

**Comment by karlfloersch** [comment]
+1 I'm having this issue as well.

**Comment by aiudirog** [comment]
@karlfloersch I ran updates just before I played with the background settings. Looking through my logs, it was a full KDE update and I see one entry in here for noto-fonts. Maybe check this against what updated for you?

Update log: http://pastie.org/10570722

**Comment by karlfloersch** [comment]
@aiudirog Sure!  Here's my update log. (I hadn't run updates for a while)  Check it out: http://pastie.org/private/dftiqqaaryfdpyy6cetcig

**Comment by karlfloersch** [comment]
This is definitely the same issue.  Notice period height.

![test](https://cloud.githubusercontent.com/assets/706123/11312494/6d857cfc-8fa4-11e5-9e8b-ca17d062376f.png)

**Comment by billiob** [comment]
This is related to harfbuzz 1.1
It is tracked on the official Terminology's bug tracker at https://phab.enlightenment.org/T2865

**Comment by aiudirog** [comment]
Damn, I was just going to say that that was one of only 4 packages that we both updated. Thanks @billiob. I'll downgrade that one for now.

**Comment by karlfloersch** [comment]
@billiob That was it!  Downgrade fixed it up. Thank you!

**Comment by aiudirog** [comment]
Just posting that the 1.1.1 update for harfbuzz does not fix this issue (was really hoping to close it:P)

**Comment by aranega** [comment]
An harfbuzz fix seems on its way :) https://github.com/behdad/harfbuzz/issues/187

**Comment by aiudirog** [comment]
@aranega Confirmed! v1.1.2 seems to have fixed the bug.
