### ISSUE TITLE
unable to active input method after enable translucent

### ISSUE THREAD

**Issue by nyim** [billiob/terminology#31]
pkg: 
1 distro: archlinux
2 terminology-0.9.1-1
3 input method: fcitx-4.2.9-2, with gtk2/gtk3

env:
GTK_MODULES=canberra-gtk-module
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
ECORE_IMF_MODULE=xim

steps to reproduce:
1. clean .config/terminology
2. set input method via enlightenment setting => language => input method
3. open terminology
4. enable translucent via setting panel => video
5. control + space, fail to active input method

steps to fix:
1 disable translucent via setting panel => video
2 restart terminology

**Comment by billiob** [comment]
If you start `terminology` with translucent support activated, does it work?

**Comment by nyim** [comment]
after enable translucent, restart terminology.
input method can't activate either

**Comment by ronchaine** [comment]
This happens to me too.  Using Arch and ibus.  Can't use input method when translucency is set.

ECORE_IMF_MODULE=xim
GTK_IM_MODULE=xim
XMODIFIERS=@im=ibus
SHELL=/bin/zsh
QT_IM_MODULE=ibus

**Comment by billiob** [comment]
Could you guys please open the bug on https://phab.enlightenment.org/maniphest/task/create/ ?

**Comment by ronchaine** [comment]
done

**Comment by qwIvan** [comment]
how can i fix the issus?

**Comment by qwIvan** [comment]
do you have any solution?

**Comment by billiob** [comment]
Follow-up is at https://phab.enlightenment.org/T3667
