### ISSUE TITLE
Split

### ISSUE THREAD

**Issue by hippytaff** [billiob/terminology#32]
Split isn't working on 0.9.0 on Moksha E17 Fork. Not sure who the bug belongs to but thought I'd flag it up. It's one of my favoritest features.

https://github.com/billiob/terminology/compare/terminology-0.9?diff=split&name=terminology-0.9

**Comment by billiob** [comment]
@hippytaff Are you talking about the `--split` option or splitting the terminal window?

**Comment by hippytaff** [comment]
The --split option

**Comment by billiob** [comment]
You should try the git version or ask for a build by the bodhilinux team. It should be fixed there.

**Comment by hippytaff** [comment]
I'll try the git version, and I'll check with Jeff to see if it's something our end. 0.8.0 works fine. Terminology is by far the best terminal emulator I've used btw, thanks :)

**Comment by hippytaff** [comment]
Fixed with 0.9.1
