### ISSUE TITLE
Focus should be on a newly created splits regardless

### ISSUE THREAD

**Issue by weitjong** [billiob/terminology#34]
Sometimes the mouse just get into the way, it usually than not hovering on top of initial window before the split is created. When a new split is created to the right (vertical split) or to the bottom (horizontal split), the position of the mouse may influence whether the newly created splits immediately getting focus or not. I know that auto-focusing on mouse hover is a feature, but in this case I haven't really touched or moved my mouse. The split is created by keyboard shortcut, so it is more intuitive to think that the focus is now in the newly created split. Focusing the split after it has been created by using ctrl+pgup|pagedown or moving my hand from keyboard to my mouse to hover/select the split is so inconvenience. I have been bitten so many times already by this since I begin to use this great terminal emulator a few days ago, finding my keystrokes ended up in the wrong split, I feel I need to log this as an issue.

**Comment by billiob** [comment]
If you have `Focus split under the mouse`, it will act like that ☹.
It's not easy to improve.

**Comment by tpham3783** [comment]
The best way to improve the focus experience (for weitjong too) is to add shortcut keys for navigation between split windows.  This feature allows the users to navigate focus across split windows only (NO TABS allowed, see https://github.com/billiob/terminology/issues/38).  We can bind Shift-Ctrl and an arrow key to select the next split window closest to the direction of selection.    The next window can be calculated from the dot product of the directional unit vector (direction of selection) and the center of gravity vector (vector that goes from the currently in-focus window and the next window).  If the result of the dot-product for multiple windows/terminals happen to be the same, the window that has the lowest magnitude calculated from the gravity vector wins!  

I believe this is a very useful feature that will make terminology superior than other terminal managers.  Please comment and let me know if it is a good idea! 

Thanks

TP

**Comment by weitjong** [comment]
Not really in favor of hacing another keyboard combo. The current default combo ctrl+pageup or down actually work as expected. My main beef about this issue is the consistency and the non-intuitiveness. The mouse should not get into way.

**Comment by tpham3783** [comment]
@weitjong - in that case for you, just turn the "Focus split under the mouse" feature off, and use ctrl-pageup/down.  

My discussion from above is about enhancing the overall experience for terminology users....  I still would like to get more feedbacks.

**Comment by weitjong** [comment]
With all due respect, I think you will get more feedbacks if you raise it as separate issue.

**Comment by billiob** [comment]
Could you guys please open bugs on https://phab.enlightenment.org/maniphest/task/create/ ?
