### ISSUE TITLE
Detach and re-attach sessions similar to screen or tmux

### ISSUE THREAD

**Issue by weitjong** [billiob/terminology#35]
This is more like a feature request than issue. Is it in the pipeline or already possible? I am still new to Terminology.

**Comment by billiob** [comment]
It is not possible. You should stick with `tmux` for that. I have no plan on implementing such a feature.

**Comment by weitjong** [comment]
Thanks for the prompt reply. Fair enough. I think I will just keep both screen/tmux and terminology in my toolbox.
