### ISSUE TITLE
Underscore character is not being rendered correctly on the last line when font is 14 pt "DejaVu Sans Mono (Book)" 

### ISSUE THREAD

**Issue by weitjong** [billiob/terminology#36]
The issue does not occur when the underscore character is on the other lines. It also does not occur with different font sizes that I have tested so far. Perhaps, 14 pt just hits a "sweet spot" for the bug to manifest itself. Additionally, it also does not occur with other fonts that I have tested so far.

I guess the calculation of the glyph height is off by one pixel or two, and so when the space is limited (the last line in the emulator) then the bug manifests itself. If so, in theory it could also happen on other fonts with other font sizes when the combo hits the "sweet spot".

**Comment by billiob** [comment]
This might be an issue with the font itself. Also try changing theme (`mild` might not have the issue).

**Comment by weitjong** [comment]
At first I also thought that the reason but it does not explain well why then it renders correctly on other lines, so I think we could rule out it is a font issue.
