### ISSUE TITLE
RFC: Change shortcut key of prev/next tab selection.

### ISSUE THREAD

**Issue by tpham3783** [billiob/terminology#38]
Hi, 

I feel that the current shortcut keys do not make too much sense for navigating between tabs.  Ctrl+page up supposes to select the next tab, however, it would select the previous tab (or the left tab); in contrast, ctrl+page down would select the previous tab (or the right tab).  The next tab should always be the tab to the right because that's the reading convention.  I would like to propose a change to the default shortcut keys of next/prev tab selections to ctrl+left and ctrl+right, respectively.  Maybe in the future, we can bind ctrl-next/previous to navigate between split windows instead.  

BTW, Konsole, a kde terminal manager, uses shortcut keys shift+left and shift+right to navigate between tabs.  I feel that most users will like binding to arrow keys (left and right), either with ctrl or shift is fine with me.  Please comment, and let me know if we should make this change.  Thank you.

**Comment by billiob** [comment]
I could add `shift+left/right` and keep `ctrl+page up/down` for people who are already used to it.

**Comment by tpham3783** [comment]
That would be great!  thanks​

**Comment by billiob** [comment]
It's added in 15fa7afaa. Thanks!
