### ISSUE TITLE
Feature request - special handling for successive enter/return key being pressed

### ISSUE THREAD

**Issue by weitjong** [billiob/terminology#39]
I like it very much how Terminology handles the successive backspace key after it hits the start of the command line buffer, i.e. flashing and showing an alarm on the right. I wonder if a similar special handling can be done for the successive enter/return key. Personally I find it really useful at some of the time to have a big gap in the screen buffer to separate between one command's output and the other. I pick up that habit after watching from a Unix admin :smile: . If I want it all the time then of course I could just create a custom shell prompt with large empty space. Here, I only need it some of the time. I wonder if it is possible that when Terminology receiving a successive enter/return key would then render some kind of vertical separator as a visual aid.

**Comment by billiob** [comment]
This should probably be done at the shell level.

**Comment by qraynaud** [comment]
@weitjong : Maybe a great idea to do this would be a "spacer" alias that just "tycat ~/.../spacer.png" that would be a beautiful line with shadows and such. Terminology already comes with great tools to achieve such a thing I think :-).

**Comment by weitjong** [comment]
That is a good idea. However, as they say, old habit die hard. I am just not sure how to alias  the "pressing/holding the ENTER key" part.

**Comment by qraynaud** [comment]
I'm not sure you can either. But maybe you can learn to type "spacer" pretty quickly?

**Comment by weitjong** [comment]
I guess so, but it kinda missing my point. Thanks anyway for the suggestion.

**Comment by billiob** [comment]
I'm closing it here. Could you guys please open the bug on https://phab.enlightenment.org/maniphest/task/create/ ?
