### ISSUE TITLE
Bold font can not be shown

### ISSUE THREAD

**Issue by cohama** [billiob/terminology#4]
I'm a Vim user and I noticed that the bold font is not correctly shown.

In the case of the result of `man` cocmmand, `NAME`, `SYSNOPTIS`, `DESCRIPTION`... are rendered by bold font in gnome-terminal, but not in terminology.

**Comment by MaximeCheramy** [comment]
Is there any update on this?

**Comment by billiob** [comment]
The good news is that I've started working on it. Might be in EFL 1.14 or most probably in EFL 1.15. If you want to help, I suggest you ask your distro maintainers to ship an up-to-date version of the EFL, elementary and terminology.

**Comment by billiob** [comment]
It is not in EFL in git. Will be shipped with EFL 1.18.
