### ISSUE TITLE
Handle text files in tycat

### ISSUE THREAD

**Issue by qraynaud** [billiob/terminology#40]
It would be great if tycat could work as cat for other files so I can make an alias cat=tycat on terminology and have it do the right thing everytime.

Bonus would be to colorize code but I won't ask for too much ;-).

P.S : terminology is great, had to say it!

**Comment by billiob** [comment]
Good idea!

**Comment by billiob** [comment]
Could you open the bug on https://phab.enlightenment.org/maniphest/task/create/ ?
