### ISSUE TITLE
Miniview over text area

### ISSUE THREAD

**Issue by qraynaud** [billiob/terminology#41]
It would be great if we could have an option for the miniview to be outside the "terminal area" meaning the text flowing down when reaching it instead of getting behind it.

At least I would love that!

**Comment by billiob** [comment]
I totally agree. I don't like the miniview for that reason. Nobody's willing to fix it ☹.

**Comment by billiob** [comment]
Could you open the bug on https://phab.enlightenment.org/maniphest/task/create/ ?

**Comment by billiob** [comment]
This is somewhat related to https://phab.enlightenment.org/T2073
