### ISSUE TITLE
Maximize not working as expected

### ISSUE THREAD

**Issue by qraynaud** [billiob/terminology#42]
I'm on KUbuntu (I know, this is a weird choice), and when I use the maximize button I often get borders staying there when they should have been removed or a window "nearly maximized" which is not perfect and thus not neat.

I attach a screenshot of the window after a maximize for you to see.

![terminology_full](https://cloud.githubusercontent.com/assets/65991/14938327/30d09aa2-0f20-11e6-969c-6e02620287d9.png)

At first I thought it was a bug between elementary and KDE but the elementary config window is working perfectly so I'm not so sure.

I hope there is an easy fix.

With regards!

(keep up with the good work: I love what you do!)

**Comment by billiob** [comment]
It's like for every `elementary` window.

**Comment by qraynaud** [comment]
Then the elementary config window is not an elementary window (it as not the bug) ? Strange ^^.

**Comment by billiob** [comment]
Could you open the bug on https://phab.enlightenment.org/maniphest/task/create/ ?
