### ISSUE TITLE
[BUG] set title of tab using shortcut key

### ISSUE THREAD

**Issue by russellchill** [billiob/terminology#43]
Boris,

This is an on going bug that I've reported to you via email already.  I want to report the bug's existence here so that we can keep track of it easier.

The bug is related to creating a new tab (ctl-alt-t) and then immediately set the title using ctrl-t.  Sometime, you'll notice Terminology will set the title of the old tab, instead of the newly created tab.  The patch below will fix this bug.  Please review the patch and feel free to comment on it.  thanks.

```
diff --git a/src/bin/win.c b/src/bin/win.c
index df3c234..43a0f3d 100644
--- a/src/bin/win.c
+++ b/src/bin/win.c
@@ -2389,7 +2389,7 @@ _tab_new_cb(void *data,
    /* XXX: need to refresh */
    tc_parent->swallow(tc_parent, tc, tc);

-   if (tc->is_focused)
+   if (tc->is_focused==EINA_FALSE)
      tc_new->focus(tc_new, tc);

    _tabs_refresh(tabs);
```

**Comment by billiob** [comment]
This can not be the correct fix.
What you're doing here is to focus the new tab if the original tab was not focused. This looks wrong.
I can't reproduce your issue at the moment but it can totally exist since the code can be racy.

**Comment by billiob** [comment]
Could you open the bug on  https://phab.enlightenment.org/maniphest/task/create/ ?

**Comment by russellchill** [comment]
Thanks, new bug report has been created at:  https://phab.enlightenment.org/T3661

**Comment by russellchill** [comment]
billiob, can you reopen this bug because it is not fixed yet.  thanks.

**Comment by billiob** [comment]
The bug should be handled on phab.enlightenment.org.
