### ISSUE TITLE
Changing font size resizes main-window when there are split terminals

### ISSUE THREAD

**Issue by tpham3783** [billiob/terminology#49]
Steps to reproduce:

1.  Launch terminology
2.  Press Ctl-shift page down to create a split window.
3.  Press Ctl-Alt - and Ctl-Alt + to change font size.
4.  Note that the main window resizes itself as you change the font size.  Also note that this behavior is not observed if there's a single term (no split windows)

Boris, let me know if you want me to report bugs like this on Phabs, thanks,

Pham

**Comment by billiob** [comment]
I'd prefer the bug reports on phab please :)
