### ISSUE TITLE
DBus error when starting terminology on a desktop

### ISSUE THREAD

**Issue by Cheezmeister** [billiob/terminology#5]
Not sure if this is your preferred bug tracker, but I ran into a small issue (well, two, see below) today launching terminology. The program starts up fine except for the error logged in the cosole:

    pts/0 % uname -a
    Linux bob-vi 3.14.5-1-ARCH #1 SMP PREEMPT Sun Jun 1 07:36:23 CEST 2014 x86_64 GNU/Linux

    pts/0 % terminology --version
    Version: 0.5.1
    ERR<1243>:efreet_cache lib/efreet/efreet_cache.c:1108 on_send_register() org.enlightenment.DBus.Canceled Canceled by user.

    pts/0 % terminology
    ERR<1196>:ecore_system_upower modules/ecore/system/upower/ecore_system_upower.c:74 _on_low_battery_get_cb() Message error org.freedesktop.DBus.Error.InvalidArgs - No such property OnLowBattery

Hope this info is useful.

**Comment by billiob** [comment]
Issues are due to EFL. Closing the issue.
