### ISSUE TITLE
Erratic behavior with Weechat

### ISSUE THREAD

**Issue by mikrobyte** [billiob/terminology#52]
This only happens when using the combination of [Terminology] + [Weechat & the buffers perl script]
the script/addon can be found here https://weechat.org/scripts/source/buffers.pl.html/

![weechat_terminology](https://cloud.githubusercontent.com/assets/17494740/16544553/661a6e8c-410b-11e6-94ba-89e1d2ff5784.png)
 
In the text input area, when typing in and deleting typed characters again, they dont get entireley deleted and previously typed-in characters remain to be seen even when they are not really there (you cannot hit enter to send them)

Also, sometimes when deleting from the text input, it starts deleting characters above in the conversation window.

Sometimes characters appear randomly in any area of the terminology screen, or some characters go missing.

This probably has to do with the buffers.pl script on top of weechat, since...this doesnt happen at all with irssi for example.

**Comment by billiob** [comment]
Are you running the git version of terminology?
