### ISSUE TITLE
Companion tools cannot use when using byobu

### ISSUE THREAD

**Issue by eggplants** [billiob/terminology#63]
When I try to `tyls` in byobu, I caught this error: "not directly running in terminology"

![image](https://user-images.githubusercontent.com/42153744/90677094-db92ee00-e297-11ea-8565-a0d119e6f669.png)

Terminology does not seem to be compatible with byobu.
Is this behavior a specification?

**Comment by billiob** [comment]
`Byoby` (or `tmux`) does not support `terminology`'s escape codes. This is the same with the `screen` utility.

**Comment by eggplants** [comment]
Okay, I try to split the screen with only terminology's utility. Thanks.

**Comment by eggplants** [comment]
s/Byoby/Byobu/
