### ISSUE TITLE
DBus error when using tycat myfile.avi

### ISSUE THREAD

**Issue by anhpht** [billiob/terminology#8]
uname -a
Linux arch 3.15.8-1-ARCH #1 SMP PREEMPT Fri Aug 1 08:51:42 CEST 2014 x86_64 GNU/Linux

terminology --version
Version: 0.6.99
ERR\<3916\>:efreet_cache lib/efreet/efreet_cache.c:1108 on_send_register() org.enlightenment.DBus.Canceled Canceled by user.

tycat myfile.avi
ERR\<3613\>:ecore_system_upower modules/ecore/system/upower/ecore_system_upower.c:74 _on_low_battery_get_cb() Message error org.enlightenment.DBus.Canceled - Canceled by user.

**Comment by billiob** [comment]
EFL issue. Should be fixed by now.
